services:
  tikkn:
    build: .
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
    volumes:
      - ${DOCKER_HOST_CERTS_DIR:-./local/certs}:/app/certs:ro
